DROP TABLE Today;
DROP TABLE Spectacle CASCADE;
DROP TABLE Organisme CASCADE;
DROP TABLE Subventions CASCADE;
DROP TABLE Cout_Spectacle CASCADE;
DROP TABLE Repre_Interne CASCADE;
DROP TABLE Billet CASCADE;
