-- Drop functions
DROP FUNCTION reserver(integer,integer);
DROP FUNCTION calc_numbre_place_dans_billet(integer);
DROP FUNCTION calc_numbre_place_dans_reserv(integer);
DROP FUNCTION get_seat_sold_percentage(integer);
DROP FUNCTION get_seat_full_percentage(integer);
DROP FUNCTION get_current_ticket_price(integer,integer);
DROP FUNCTION pay_reservation(integer,integer,integer);
DROP FUNCTION account(integer,integer);
DROP FUNCTION account_by_repre(integer,integer);
DROP FUNCTION account_by_date(integer,date,date);
DROP FUNCTION balance_sheet(integer,date,date);
